# Generated by Django 6.0.4 on 2026-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classsession_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-time_in']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.DateTimeField(),
        ),
    ]
