# Generated by Django 6.0.4 on 2026-04-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_attendance_options_alter_attendance_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
