# Generated by Django 6.0.4 on 2026-04-16 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0002_pendingrfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Format: YYYY-XXXXX (e.g., 2022-00779)', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be in format: YYYY-XXXXX (e.g., 2022-00779)', regex='^\\d{4}-\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only @wmsu.edu.ph email addresses are allowed', regex='^[^\\s@]+@wmsu\\.edu\\.ph$')]),
        ),
    ]
